hasstorage: true
ispayable: false
events:
  - name: containerPut
    parameters:
      - name: container
        type: ByteString
      - name: signature
        type: ByteString
      - name: publicKey
        type: ByteString
  - name: containerDelete
    parameters:
      - name: containerID
        type: ByteString
      - name: signature
        type: ByteString
