hasstorage: true
ispayable: false
events:
  - name: containerPut
    parameters:
      - name: container
        type: ByteArray
      - name: signature
        type: ByteArray
      - name: publicKey
        type: ByteArray
  - name: containerDelete
    parameters:
      - name: containerID
        type: ByteArray
      - name: signature
        type: ByteArray
  - name: StartEstimation
    parameters:
      - name: epoch
        type: Integer
  - name: StopEstimation
    parameters:
      - name: epoch
        type: Integer
