hasstorage: true
ispayable: false
events:
  - name: Lock
    parameters:
      - name: txID
        type: ByteArray
      - name: from
        type: ByteArray
      - name: to
        type: ByteArray
      - name: amount
        type: Integer
      - name: until
        type: Integer
  - name: transfer
    parameters:
      - name: from
        type: ByteArray
      - name: to
        type: ByteArray
      - name: amount
        type: Integer
  - name: transferX
    parameters:
      - name: from
        type: ByteArray
      - name: to
        type: ByteArray
      - name: amount
        type: Integer
      - name: details
        type: ByteArray
  - name: Mint
    parameters:
      - name: from
        type: ByteArray
      - name: amount
        type: Integer
  - name: Burn
    parameters:
      - name: to
        type: ByteArray
      - name: amount
        type: Integer