name: "NeoFS Subnet"
safemethods: ["version"]
permissions:
  - methods: ["update"]
events:
  - name: Put
    parameters:
      - name: id
        type: ByteArray
      - name: ownerKey
        type: PublicKey
      - name: info
        type: ByteArray
  - name: Delete
    parameters:
        - name: id
          type: ByteArray
  - name: RemoveNode
    parameters:
        - name: subnetID
          type: ByteArray
        - name: node
          type: PublicKey
