name: "NeoFS Subnet"
safemethods: ["version"]
permissions:
  - methods: ["update"]
events:
  - name: Delete
    parameters:
        - name: id
          type: ByteArray
  - name: RemoveNode
    parameters:
        - name: subnetID
          type: ByteArray
        - name: node
          type: PublicKey
