package nns

import "math/big"

// Record types are defined in [RFC 1035](https://tools.ietf.org/html/rfc1035)
// These variables are provided to be used with autogenerated NNS wrapper that
// accepts *big.Int for record type parameters, values MUST NOT be changed.
var (
	// A represents address record type.
	A = big.NewInt(1)
	// CNAME represents canonical name record type.
	CNAME = big.NewInt(5)
	// SOA represents start of authority record type.
	SOA = big.NewInt(6)
	// TXT represents text record type.
	TXT = big.NewInt(16)
)

// Record types are defined in [RFC 3596](https://tools.ietf.org/html/rfc3596)
// These variables are provided to be used with autogenerated NNS wrapper that
// accepts *big.Int for record type parameters, values MUST NOT be changed.
var (
	// AAAA represents IPv6 address record type.
	AAAA = big.NewInt(28)
)
