package nns

import (
	"math/big"

	"github.com/nspcc-dev/neofs-contract/contracts/nns/recordtype"
)

// Record types are defined in [RFC 1035](https://tools.ietf.org/html/rfc1035)
// These variables are provided to be used with autogenerated NNS wrapper that
// accepts *big.Int for record type parameters, values MUST NOT be changed.
var (
	// A represents address record type.
	A = big.NewInt(int64(recordtype.A))
	// CNAME represents canonical name record type.
	CNAME = big.NewInt(int64(recordtype.CNAME))
	// SOA represents start of authority record type.
	SOA = big.NewInt(int64(recordtype.SOA))
	// TXT represents text record type.
	TXT = big.NewInt(int64(recordtype.TXT))
)

// Record types are defined in [RFC 3596](https://tools.ietf.org/html/rfc3596)
// These variables are provided to be used with autogenerated NNS wrapper that
// accepts *big.Int for record type parameters, values MUST NOT be changed.
var (
	// AAAA represents IPv6 address record type.
	AAAA = big.NewInt(int64(recordtype.AAAA))
)
